chore: simplify construction event handlers + few functions
bahrmichael/factorio-tycoon pull request #308
Opened 2024-04-03 21:13 UTC by winex

don't squash, please. best to be merged after #307 is in

_this is picked from destroy event fix #300, which depends on it_

2024-04-03 21:19 UTC, winex reviewed
:+1:, though your `luacheck` hates me :p

2024-04-03 21:19 UTC, winex commented on construction-event-handler.lua
this diff looks horrible, it's better to view whole file

2024-04-10 08:43 UTC, bahrmichael commented
@winex I added `serpent` to the luacheckrc. You can pull the latest updates to make the build green :)

2024-04-10 19:48 UTC, winex commented
@bahrmichael rebased, _coding speedrun is_ green now :)

2024-04-15 15:39 UTC, bahrmichael requested changes
Would it be possible to avoid goto statements? I'm not aware if there's anything requiring those, and prefer if/else statements over jumps across the code.

2024-04-16 01:48 UTC, winex commented
> Would it be possible to avoid goto statements? I'm not aware if there's anything requiring those, and prefer if/else statements over jumps across the code.

yep, changed. `goto`'s aren't my preference as well, but sometimes it simplifies **cleanup** code paths to just few lines... that's why i used it here - it just states that you never forget one last thing(s).

though, as Lua doesn't have `continue` statement (lol) i still use close-jump `goto`s sometimes in loops to minimize `if-then` nesting

2024-04-16 07:10 UTC, bahrmichael approved these changes
Thank you for the refactoring!

2024-04-16 07:11 UTC, merged